[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["pip install -r backend_app/requirements.txt"]

[phases.build]
cmds = ["cd backend_app && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend_app && gunicorn vidnex_platform.wsgi --bind 0.0.0.0:$PORT --log-file -"
