[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn vidnex_platform.wsgi --bind 0.0.0.0:$PORT --chdir backend_app --log-file -"
